package split.dashdash.com.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import split.dashdash.com.model.Bill;

import split.dashdash.com.model.BillDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig billDaoConfig;

    private final BillDao billDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        billDaoConfig = daoConfigMap.get(BillDao.class).clone();
        billDaoConfig.initIdentityScope(type);

        billDao = new BillDao(billDaoConfig, this);

        registerDao(Bill.class, billDao);
    }
    
    public void clear() {
        billDaoConfig.getIdentityScope().clear();
    }

    public BillDao getBillDao() {
        return billDao;
    }

}
